### ISSUE TITLE
Status of setup trouble with JSignPdf version

### ISSUE THREAD

**Issue by Thibtib51** [LibreSign/libresign#1264]
Hi all,
I have trouble to install JSignPdf in my seflhosted Nextcloud (25.0.1).
I download the application with Nextcloud appstore, going into Admin/LibreSign and like README.md click on Download binaires. But here I have first trouble, at the end, the button called Binaries Downloaded and pass to Download binaries.
Below in Status of setup nothing change.
I going to SSH and install LibreSign using occ commands (sudo -u www-data php occ libresign:install --all).
After that, I have all in green in status of setup (except CFSSL) and except "Necessary install the version 2.2.0" but below I have in green "JSignPdf version:".
I can install CFSSL but the issue "Necessary install the version 2.2.0" still red

Hope you can help me.

I keep in touch ;)

**Comment by vitormattos** [comment]
Hi @Thibtib51 
I think that all was well. I identified this problem in specific environments and fixed here: https://github.com/JSignPdf/jsignpdf-php/pull/16. I think that isn't a real problem, only is a problem to parse the version number of JSignPdf.
Proceed with the setup of Root certificate in the same screen.

**Comment by Thibtib51** [comment]
Hi @vitormattos 
Write you're right is working. I will try LibreSign later because an external email contact must create a Nextcloud account to signed a document. And during my first test after typing password I have a error. 
Unfortunately I don't have much time to try to find it. Hope later and you will provide a some update.
Thank you again for your help

**Comment by nonofr91** [comment]
Hello, sorry for my English, I use google translate. I also have this problem it seems. I can't remove the error message (N°1 below) in the libresign setting. However, I executed the command in a console of the container.
And during my test I have an error in the nextcloud logs (N°2 below). I anonymized the information. I hope this information will help you find the problem. Thank you for your work.

N°1:     error	Necessary install the version 2.2.0	jsignpdf	Run occ libresign:install --jsignpdf


N°2:    [libresign] Erreur: Error to sign PDF. ["sh: \/data\/appdata_ocnahsfazjip\/libresign\/java\/jdk-17.0.5+8-jre\/bin\/java: not found"]

POST /apps/libresign/api/0.1/sign/uuid/a7498277-341e-4a72-bd0a-663300e4eef8
from _(IP Public)_ (mail of user) at 2022-12-11T08:25:20+00:00

**Comment by nonofr91** [comment]
> Bonjour, désolé pour mon anglais, j'utilise google translate. J'ai aussi ce problème il me semble. Je n'arrive pas à supprimer le message d'erreur (N°1 ci-dessous) dans le paramétrage libresign. Cependant, j'ai exécuté la commande dans une console du conteneur. Et lors de mon test j'ai une erreur dans les logs de nextcloud (N°2 ci-dessous). J'ai anonymisé l'information. J'espère que ces informations vous aideront à trouver le problème. Merci pour votre travail.
> 
> N°1 : erreur Nécessité d'installer la version 2.2.0 jsignpdf Lancer occ libresign:install --jsignpdf
> 
> N°2 : [libresign] Erreur : Erreur de signature de PDF. ["sh : /data/appdata_ocnahsfazjip/libresign/java/jdk-17.0.5+8-jre/bin/java : introuvable"]
> 
> POST /apps/libresign/api/0.1/sign/uuid/a7498277-341e-4a72-bd0a-663300e4eef8 de _(IP Public)_ (mail de l'utilisateur) au 2022-12-11T08:25:20+00:00

Further information:
the java file is present on my machine. But I use docker and I checked in console mode if the java is fine. it is OK for me. why can't he see?

**Comment by nonofr91** [comment]
> occ libresign:install --all

Hello, yes I just tried and I have the same error.

**Comment by unnilennium** [comment]
same here NC24. 
occ libresign:install --jsignpdf did turn it green but as soon as I filled the certificate info, turn red again

on checks I get twice
/apps/libresign/api/0.1/admin/configure-check","message":"implode(): Invalid arguments passed at /usr/share/nextcloud/apps/libresign/lib/Service/ConfigureCheckService.php#160","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0","version":"24.0.7.1","exception":{"Exception":"Error","Message":"implode(): Invalid arguments passed at /usr/share/nextcloud/apps/libresign/lib/Service/ConfigureCheckService.php#160"

**Comment by vitormattos** [comment]
As explained, this isn't a real problem, is only a problem when parse the version number of JSignPdf and don't affect the work of LibreSign.

About the support to Nextcloud 24, we dropped this support because we haven't any customer paying to maintain this release and is a bit hard to us to do this for free. We recommend migrate to Nextcloud 25 to use LibreSign.

**Comment by vitormattos** [comment]
Fixed in version 6.2.1

**Comment by kmorber** [comment]
Still not working1

**Comment by pwepwe973** [comment]
hello, 

me neither it still doesn't work too bad a very nice plugin for nextcloud and very promising
