### ISSUE TITLE
Invalid Hash of binaries files.

### ISSUE THREAD

**Issue by GauthierCrp** [LibreSign/libresign#3230]
Hello,

First, many thanks for your job, it's a great tool to use !

On Nexcloud Hub 8, the installation goes wrong. The different binaries, are well downloading, but impossible de pass de check verification.

![image](https://github.com/LibreSign/libresign/assets/30144651/ad32e44a-75f3-4a11-8b3c-6874a240ddd5)

I installed Libresign from the Nextcloud's store.
If used the occ command to download every binaries without any error. But the check status, is still to error. 

![image](https://github.com/LibreSign/libresign/assets/30144651/6daa3741-4134-4dab-8348-2995838b9810)

![image](https://github.com/LibreSign/libresign/assets/30144651/92f9f8dd-c920-40d4-87a2-671a44ae038b)

If someone can help me to get the installation working !

Thank you, very much in advance :)

Best Regards

**Comment by vitormattos** [comment]
Thanks by your report, I will check what's happening. This is a new feature.

**Comment by vitormattos** [comment]
I identified the problem. This version need to have json files signing the dependencies but looking at tar.gz file, haven't the necessary files.

|Current scenario|Need to have these files|
|---|---|
|![Screenshot_20240626_094958](https://github.com/LibreSign/libresign/assets/1079143/3e11b31f-8e78-49e8-b8e2-e4045055161a)|![Screenshot_20240626_095205](https://github.com/LibreSign/libresign/assets/1079143/7981a381-cfcb-418c-ade3-567d3c8f1521)|

I will check how to solve. The problem is when LibreSign is packed to publish at Nextcloud app store.

**Comment by vitormattos** [comment]
@GauthierCrp could you test the newest release?

**Comment by GauthierCrp** [comment]
Hello Vitor,

The bug seems to be resolved ! Many Thanks !

![image](https://github.com/LibreSign/libresign/assets/30144651/1e40514e-543b-4c41-93c5-06a9b0210f8c)

Have a good day.
Best Reagrd

**Comment by AceDicer** [comment]
@vitormattos Fixed the invalid hashes on my instance as well.


That said, I can't seem to find how to add a signature to a pdf. The option "Open in LibreSign" opens the file info menu onto the LibreSign tab, but it is empty with no actions available.


![Image](https://github.com/LibreSign/libresign/assets/8314961/2652d78e-d72a-4619-9889-a4adcc5d2342)

**Comment by vitormattos** [comment]
@AceDicer This isn't about this issue. Could you open a specific issue to this?

**Comment by rodsmar** [comment]
@vitormattos hey, i have a trouble with this error, even after upgrading to 9.1.2.

If i remove these lines:

`//                      if (count($this->verify('java'))) {
//                              return [
//                                      (new ConfigureCheckHelper())
//                                              ->setErrorMessage(
//                                                      'Invalid hash of binaries files.'
//                                              )
//                                              ->setResource('java')
//                                              ->setTip('Run occ libresign:install --all'),
//                              ];
//                      }
`

The things goes in right way!

I guess the java file check doesn't works.

**Comment by vitormattos** [comment]
Hi @rodsmar I think that I identified another problem at build and fixed here:
- https://github.com/LibreSign/libresign/pull/3250
I already merged this but I'm working now to generate a new build.

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by jameswlane** [comment]
I am using the latest version `9.1.3` and still having issue with `Invalid hash of binaries files.`


![image](https://github.com/LibreSign/libresign/assets/794161/ea377bdc-6e41-44d7-8b24-8215ad673c3a)

**Comment by vitormattos** [comment]
@jameswlane I'm starting to create a new release with points that will touch at this.

Is your environment with debug mode on?

**Comment by vitormattos** [comment]
I created a new release now, could you check with the newest release?

**Comment by jameswlane** [comment]
It seems to be stuck in a loop of download and validate

[Screencast from 2024-07-11 12-53-01.webm](https://github.com/LibreSign/libresign/assets/794161/15cb2563-6a55-454f-9ceb-16d10cdca3ce)

**Comment by jameswlane** [comment]
@vitormattos Any idea on what I can try to resolve the loop?

**Comment by vitormattos** [comment]
Are you using Alpine Linux?

**Comment by vitormattos** [comment]
I created a new release with some fixes at setup flow, could you check with the newest release?

**Comment by jameswlane** [comment]
@vitormattos I am using `Ubuntu 22.04 LTS`. I will update it and see what I get.

**Comment by jameswlane** [comment]
@vitormattos Same thing. I ssh in and grabbed the logs its throwing the following error:
```bash
file_get_contents(): Read of 12288 bytes failed with errno=21 Is a directory at /var/www/html/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#44 
```

**Comment by rodsmar** [comment]
After upgrading to 9.2.2 i can confirm: Java's hash validation works flawless!

But...

To check requirements i had to enable Nextcloud's debug mode:

`config:system:set debug --value true --type boolean`

**Comment by vitormattos** [comment]
@rodsmar the signature process is to ensure that the downloaded files are certified to works with LibreSign and wasn't changed.

At development mode is necessary to enable the debug mode because a developer can't sign the downloaded, only the LibreSign author that have the certificate can sign the downloaded files. At development mode is used a self generated certificate to sign and validate the downloaded files.

The signatures of downloaded files are stored at folder appinfo inside LibreSign folder. Are a lot of *.json files. These fiels are generated during the build process of LibreSign to validate the signatuer by the same way of Nextcloud validate the apps that are signed by developer certificate.

I think that have anything different at your environment. Could you check at Administratin Settings if all checks of Nextcloud are ok? Isn't the check of LibreSign, is about the checks of Nextcloud. I think that when you defined debug=true and validated your LibreSign setup, changed the json files inside appinfo folder.

**Comment by vitormattos** [comment]
Closing this as solved after newest release.

Please, test again to check if all is working fine.

**Comment by Fuseteam** [comment]
> [@Fuseteam](https://github.com/Fuseteam) check if your java version is up to date.

I just ran occ libresign:install --all last week so i believe it should be up to date

**Comment by ayubwaheed** [comment]
nextcloud running in Truenascale apps

Ran php occ libresign:install -all but jsignpdf still not valid hash. Any asistance for fix !!

![Image](https://github.com/user-attachments/assets/04464561-e114-4ace-ae6e-af04e063549b)

**Comment by Fuseteam** [comment]
there is now an fix for this issue: https://github.com/LibreSign/libresign/issues/4810#issuecomment-2989422713

It turns out that the downloaded binaries in `/var/html/data/appdata_*/libresign/x86_64/jsignpdf` are corrupted, removing those binaries manually and then re-running `libresign:install --all` fixes the error
